version: '3'

services:
  ngbackdev:
    container_name: 'TRYBE_ngBackDev'
    build: ./ngBackDev
    ports:
      - 3001:3001
    command: yarn dev
    environment:
      - PORT=3001
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_HOST=database
      - DB_NAME=NGAPP
      - DB_PORT=5432
    healthcheck:
      test: ['CMD', 'lsof', '-i', ':3001']
      timeout: 10s
      retries: 5

  # frontend:
  #   container_name: 'TRYBE_frontend'
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - REACT_APP_HOST = http://frontend:3000
  #     - REACT_APP_API = http://ngBackDev:3001

  database:
    container_name: 'TRYBE_postgres'
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=NGAPP
    restart: 'always'
    healthcheck:
      test: ['CMD', 'dmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  default:
    # Use a custom driver
    driver: bridge
